[package]
name = "query_executor"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"
publish = false

[dependencies]
ast = { path = "../ast" }
binary = { path = "../binary" }
constraints = { path = "../constraints" }
data_manager = { path = "../data_manager" }
expr_eval = { path = "../expr_eval" }
kernel = { path = "../kernel" }
meta_def = { path = "../meta_def" }
metadata = { path = "../metadata" }
plan = { path = "../plan" }
protocol = { path = "../protocol" }
repr = { path = "../repr" }
sql_model = { path = "../sql_model" }

bigdecimal = { version = "0.2.0", features = ["string-only"] }
futures-lite = "1.10.1"
log = "0.4.11"
sqlparser = { git = "https://github.com/ballista-compute/sqlparser-rs.git", branch = "main", features = ["bigdecimal"] }

[dev-dependencies]
rstest = "0.6.4"
tempfile = "3.1.0"
