[package]
name = "sql_engine"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"
publish = false

[dependencies]
log = "0.4.8"
kernel = { path = "../kernel" }
storage = { path = "../storage" }
sqlparser = { version = "0.6.1", features = ["bigdecimal"] }
bigdecimal = "0.1.2"
sql_types = { path = "../sql_types" }
protocol = { path = "../protocol" }
futures-lite = "1.0.0"
representation = { path = "../representation" }
serde = { version = "1.0.114", features = ["derive"] }
bincode = "1.3.1"

[dev-dependencies]
rstest = "0.6.4"
tempfile = "3.1.0"
