[package]
name = "metadata"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"
publish = false

[dependencies]
binary = { path = "../binary" }
meta_def = { path = "../meta_def" }
pg_model = { path = "../pg_model" }
repr = { path = "../repr" }
sql_model = { path = "../sql_model" }
storage = { path = "../storage" }

dashmap = "3.11.10"
log = "0.4.11"

[dev-dependencies]
backtrace = "0.3.55"
rstest = "0.6.4"
tempfile = "3.1.0"
