[package]
name = "pg_model"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"
publish = false

[dependencies]
bigdecimal = { version = "0.2.0", features = ["string-only"] }
byteorder = "1.3.4"
# TODO get rid off dependency
sqlparser = { git = "https://github.com/ballista-compute/sqlparser-rs.git", branch = "main", features = ["bigdecimal"] }
pg_wire = "0.4.0"
rand = "0.7"

[dev-dependencies]
rstest = "0.6.4"
