[package]
name = "node"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"
publish = false

[lib]
name = "node"

[[bin]]
name = "database"
path = "src/bin.rs"

[dependencies]
kernel = { path = "../kernel" }
sql_engine = { path = "../sql_engine" }
sql_model = { path = "../sql_model" }
data_manager = { path = "../data_manager" }
futures-lite = "1.4.0"
smol = "1.0.0"
async-io = "1.1.0"
protocol = { path = "../protocol" }
log = "0.4.8"
simple_logger = { version = "1.9.0", default-features = false }
async-dup = "1.2.1"
blocking = "1.0.0"
