[package]
name = "plan"
version = "0.1.0"
authors = ["Alex Dukhno <alex.dukhno@icloud.com>"]
edition = "2018"
publish = false

[dependencies]
ast = { path = "../ast" }
constraints = { path = "../constraints" }
meta_def = { path = "../meta_def" }
pg_wire = "0.3.1"
sql_model = { path = "../sql_model" }

sqlparser = { git = "https://github.com/ballista-compute/sqlparser-rs.git", branch = "main", features = ["bigdecimal"] }
